### ISSUE TITLE
TableRegistory::get is deprecated from cake 3.6.x

### ISSUE THREAD

**Issue by supermanner** [itosho/easy-query#17]
## Topic
- When cakephp is updated for 3.6.x,  we don't use  `TableRegistory::get('yourTableName')`, but  `$this->getTableLocator()->get('yourTableName')` 
- So, Please update the point of that 👆 in README.md

**Comment by itosho** [comment]
@supermanner Thanks! Fixed!
https://github.com/itosho/easy-query/pull/18
